version: '3'

services:
  docker-cosmos:
    container_name: cosmos_testnet
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - MONIKER=NodeName
      - CHAIN_ID=gaia-13003
      - GENESIS_URL=https://raw.githubusercontent.com/cosmos/testnets/master/gaia-13k/genesis.json
      - SEEDS=ed9276861553e796bc17729f6be4a3f7626d68f1@digiderivatives.com:26656
      # - GAIAD_HOME=/.gaiad
      # - ADDR_BOOK_STRICT=false
      # - CACHE_SIZE=10000
    ports:
      - "26656:26656"
      - "26657:26657"
      - "26658:26658"
      - "1317:1317" # for rest-server
    volumes:
      - testnet_config:/.gaiad/config
      - testnet_keys:/.gaiacli/keys
volumes:
  testnet_config:
  testnet_keys:
