version: '3'

services:
  cosmos-testnet:
    container_name: cosmos-testnet
    build:
      context: .
      dockerfile: Dockerfile-testnet
    environment: 
      - MONIKER=NodeName
      - CHAIN_ID=gaia-13006
      - GENESIS_URL=https://raw.githubusercontent.com/cosmos/testnets/master/gaia-13k/genesis.json
      - SEEDS=17c443c877662296fd46f67b6a1a27a4821b996a@highfrequencystaking.com:26656
      - CACHE_SIZE=50000
      - GRPC_MAX_OPEN_CONNECTIONS=2100
      - MAX_OPEN_CONNECTIONS=0
      - GAIAD_HOME=/.gaiad
      - MAX_SUBSCRIPTION_PER_CLIENT=25
      # - ADDR_BOOK_STRICT=false
      # - LCD_PORT=3317
      # - RPC_LADDR_PORT=36657
      # - CONNECTIONS_LADDR_PORT=36656
      # - PROXY_APP_PORT=36658
      # - BOOTSTRAP=FALSE
    restart: always
    ports:
      - "26656:26656"
      - "26657:26657"
      - "26658:26658"
      - "1317:1317" # for rest-server
    volumes:
      - cosmos-testnet-data:/.gaiad
volumes:
  cosmos-testnet-data:
